### ISSUE TITLE
Contracts functionality

### ISSUE THREAD

**Issue by ihorbond** [hossyposs/Etherscan.Net#2]
Hey nice package! Do you consider adding Contracts functionality in the near future ? If not can I create a PR and add it in ? I'm interested in smart contract verification

**Comment by hoss-green** [comment]
Hey Ihor,

Please feel free to open a PR, I'm a little swamped at the moment, but I'm planning on adding in tests sometime in the next few weeks, so any PR's to expand functionality would be great as it frees up my time for test-writing (the fun stuff :/)!

best,

Hoss

**Comment by ihorbond** [comment]
Hey @hossyposs please look at the PR #4  I actually need other block explorers like fantom and avax as well. can we add those as well ? do you foresee any issues ?

**Comment by hoss-green** [comment]
Looking at the code, I don't see any technical issues, only one comment is for consistency I would use "Abi", not "ABI", for example "GetContractAbi" not "GetContractABI". If you're happy to make the change, I can merge. Everything else looks good.

**Comment by ihorbond** [comment]
@hossyposs np I fixed that also added smart contract verification since I will need that as well but this code throws an error here for this request
https://docs.etherscan.io/api-endpoints/contracts#check-source-code-verification-submission-status
even though the request was completed successfully (code 200) the Etherscan response is NOTOK, result: Pending in queue. Do we want to leave it like that ? 
![image](https://user-images.githubusercontent.com/15573624/149048534-65f66da3-7196-4ce7-b61b-1b9aa7dc85d8.png)

**Comment by hoss-green** [comment]
@ihorbond That's a tricky one. I guess that Etherscan should be returning a "OK" response "Pending in queue"? Maybe we should highlight this as an issue on their end. 

Not sure who is best to contact regarding this. Any ideas?

**Comment by hoss-green** [comment]
Although, short answer, I think leave as is. Regarding the merge, is there anything else you'd like to add, or should I review this fully now?

**Comment by ihorbond** [comment]
@hossyposs yes ready to review, thanks

**Comment by hoss-green** [comment]
Merged and done
